#!/bin/bash
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg VCS_URL=`git remote get-url origin` \
             --build-arg VERSION=$SOURCE_BRANCH -t $IMAGE_NAME .
