name: dockerhub

on:
  release:
    types: [ published ]

env:
  project: 'gun'

jobs:

  dockerhub:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        docker build -t ${{ env.project }} .

    - name: Login
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build
      run: |
        echo "SHA=$GITHUB_SHA"
        docker build --build-arg \
          SHA=$GITHUB_SHA \
          BUILD_DATE=$(date +'%Y-%m-%d') \
          VCS_REF=${GITHUB_REF/refs\/tags\/v/} \
          VCS_URL=$GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} \
          VERSION=${GITHUB_REF/refs\/tags\/v/} \
          --label "sha=$GITHUB_SHA" \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.project }}:${GITHUB_REF/refs\/tags\/v/} \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.project }}:latest \
          .

    - name: Push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.project }}
